-- Additional SELECT 함수

-- 1번
SELECT STUDENT_NO "학번", STUDENT_NAME "이름", TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') "입학년도"
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE ;

-- 2번
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';

-- 3번 ************************다시 풀기************************
SELECT PROFESSOR_NAME "교수이름", 
	FLOOR(MONTHS_BETWEEN(SYSDATE,TO_DATE(SUBSTR(PROFESSOR_SSN,1,6)))/12) "나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1) = '1'
AND TO_DATE(SUBSTR(PROFESSOR_SSN,1,6), 'RRRRMMDD') <= TO_DATE('1999-12-31','RRRRMMDD')
--1999/12/31 출생자까지
ORDER BY PROFESSOR_SSN;

-- 4번
SELECT SUBSTR(PROFESSOR_NAME, 2) "이름"
FROM TB_PROFESSOR;

-- 5번 ****** WHERE
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE (MONTHS_BETWEEN(ENTRANCE_DATE,TO_DATE(SUBSTR(STUDENT_SSN,1,6)))/12) > 19;
-- 입학년도-주민번호 > 19

SELECT CEIL(MONTHS_BETWEEN(ENTRANCE_DATE,TO_DATE(SUBSTR(STUDENT_SSN,1,6)))/12)
FROM TB_STUDENT;

-- 6번 
SELECT TO_CHAR(TO_DATE('201225'), 'YYYY/MM/DD DAY') "2020년 크리스마스"
FROM DUAL;

-- 7번
-- TO_DATE('99/10/11','YY/MM/DD'): 2099년 10월 11일
-- TO_DATE('49/10/11','YY/MM/DD'): 2049년 10월 11일
-- TO_DATE('99/10/11','RR/MM/DD'): 1999년 10월 11일
-- TO_DATE('49/10/11','RR/MM/DD'): 1949년 10월 11일

-- 8번
SELECT
FROM

-- 9번
SELECT
FROM

-- 10번
SELECT
FROM

-- 11번
SELECT
FROM

-- 12번
SELECT
FROM

-- 13번
SELECT
FROM

-- 14번
SELECT
FROM
