-- Additional SELECT 함수

-- 1번
SELECT STUDENT_NO "학번", STUDENT_NAME "이름", TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') "입학년도"
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE ;

-- 2번
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';

-- 3번 ************************다시 풀기************************
SELECT PROFESSOR_NAME "교수이름", 
	FLOOR(MONTHS_BETWEEN(SYSDATE,TO_DATE(SUBSTR(PROFESSOR_SSN,1,6)))/12) "나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1) = '1'
AND TO_DATE(SUBSTR(PROFESSOR_SSN,1,6), 'RRRRMMDD') <= '1999-12-31'
--1999/12/31 출생자까지
ORDER BY PROFESSOR_SSN;

-- 4번
SELECT SUBSTR(PROFESSOR_NAME, 2) "이름"
FROM TB_PROFESSOR;

-- 5번
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE -- 입학년도-주민번호 > 19

-- 6번
SELECT TO_DATE('20/12/25', 'YY/MM/DD')
FROM DUAL;

-- 7번
SELECT
FROM

-- 8번
SELECT
FROM

-- 9번
SELECT
FROM

-- 10번
SELECT
FROM

-- 11번
SELECT
FROM

-- 12번
SELECT
FROM

-- 13번
SELECT
FROM

-- 14번
SELECT
FROM
